[package]
name = "sign"
version = "0.1.1"
edition = "2021"

[dependencies]
chrono = "0.4.22"
serde_json = { version = "1.0.85", features = ["preserve_order"] }
openssl = "0.10.41"
url = "2.2.2"
thiserror = "1.0.33"
