[package]
name = "cf-sign"
version = "0.1.1"
edition = "2021"

[workspace]

[dependencies]
sign = { path = "sign" }
anyhow = "1.0.63"
clap = { version = "3.2.20", features = ["derive"] }
url = "2.2.2"
chrono = "0.4.22"

[profile.release]
debug = false
debug-assertions = false
overflow-checks = false
panic = 'unwind'
incremental = false
rpath = false
opt-level = 3
lto = "fat"
codegen-units = 1

